### ISSUE TITLE
Get message quail error pfs import: decordePrt ddv.prt: invalid version 3, wanted 4+, also shows on other GoD/OoW creatures import

### ISSUE THREAD

**Issue by 5000thinmints** [xackery/quail-addon#9]
I get that error message on importing a girplan as well as other GoD/OoW creatures, for example the feran fra.eqg, taloesan tln.eqg, or mata muram at clv also fail to load, though murkglider dma.eqg imports just fine for a case that works.  

Running Blender 3.6.0 on Windows 10 enterprise. Gives the same error message under blender 4.1.0 and 3.0.0.

**Comment by xackery** [comment]
Howdy,
thanks for trying out quail!..

There's a lot of unsupported features in quail for eqg that quail did not quite ever cover. At this time, quail is being reworked with a major refactor.  You can see active chats related to it and other projects on the eqemu discord here https://discord.com/channels/212663220849213441/924818607303716956
